#!/usr/bin/env python3
from ex1 import HealingCreatureFactory, TransformCreatureFactory


print("Testing Creature with healing capability")
heal_factory = HealingCreatureFactory()
sproutling = heal_factory.create_base()
print(" base:")
print(sproutling.describe())
print(sproutling.attack())
print(sproutling.heal())
print(" evolved:")
bloomelle = heal_factory.create_evolved()
print(bloomelle.describe())
print(bloomelle.attack())
print(bloomelle.heal())
print()
print("Testing Creature with transform capability")
print(" base:")
trans_factory = TransformCreatureFactory()
shiftling = trans_factory.create_base()
print(shiftling.describe())
print(shiftling.attack())
print(shiftling.transform())
print(shiftling.attack())
print(shiftling.revert())
print(" evolved:")
morphagon = trans_factory.create_evolved()
print(morphagon.describe())
print(morphagon.attack())
print(morphagon.transform())
print(morphagon.attack())
print(morphagon.revert())
